{
 "title": "WaterBox 90.3",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "PH",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as ph, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'ph' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as temperature, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'temperature' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Calcium",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as calcium, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'calcium' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Alkalinity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as alkalinity, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'alkalinity' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Magnesium",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as magnesium, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'magnesium' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Phosphate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as Phosphate, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'phosphate' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Nitrate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as Nitrate, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'nitrate' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  }
 ]
}